# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='predefined_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
